# Generated by Django 5.0.4 on 2024-06-01 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointmentinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('contactno', models.IntegerField()),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Doctorinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_image', models.ImageField(upload_to='doctors/')),
                ('doctor_name', models.CharField(max_length=100)),
                ('doctor_spec', models.CharField(max_length=100)),
            ],
        ),
    ]
