# Generated by Django 5.0.4 on 2024-06-01 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_appointmentinfo_doctorinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentinfo',
            name='doctor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapp.doctorinfo'),
        ),
    ]
