# Generated by Django 5.0.4 on 2024-06-01 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_appointmentinfo_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentinfo',
            name='doctor',
            field=models.CharField(max_length=100),
        ),
    ]
